//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_clement
{
    using System;
    using System.Collections.Generic;
    
    public partial class articles
    {
        public string titre { get; set; }
        public string contenu { get; set; }
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
