//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_clement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.articles = new HashSet<articles>();
        }
    
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> Naissance { get; set; }
        public string Numero { get; set; }
        public Nullable<decimal> Departement { get; set; }
        public int userId { get; set; }
    
        public virtual ICollection<articles> articles { get; set; }
    }
}
